FROM golang:1.21 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./
COPY internal ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /mschemaguesser

FROM build-stage AS run-test-stage

RUN go test -v ./...
