FROM golang:1.21 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -o /mschemaguesser cmd/schemaguesser/main.go

FROM build-stage AS run-test-stage

RUN go test -v --skip "_IT" ./...

CMD ["go", "test", "-v", "./..."]
