version: '3'
services:
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

  mongo_init:
    image: mongo:4
    depends_on:
      - mongodb
    command: ["/prepare_mongo.sh", "dev"]
    volumes:
      - ./resources/init.js:/initdb.d/init.js
      - ./resources/prepare_mongo.sh:/prepare_mongo.sh
    healthcheck:
      test: ["CMD-SHELL", "cat /done.txt"]
      interval: 5s
      timeout: 1s
      retries: 100

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secretpassword
