name: Publish docker image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build image
        run: ./buildImage.sh
      - name: Login to GitHub Registry
        run: echo ${{ secrets.GH_PUBLISH_TOKEN }} | docker login ghcr.io -u okieoth --password-stdin
      - name: Push the Docker image
        run: docker push ghcr.io/okieoth/mschemaguesser:`cat version.txt | grep -P '\d+\.\d+\.\d+'`
      - name: Push the latest Docker image
        run: docker push ghcr.io/okieoth/mschemaguesser
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GH_PUBLISH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
