name: mschemaguesser tests

on:
  pull_request:
    branches: [main]

jobs:
  test_on_pr:
    runs-on: ubuntu-latest
    name: test
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker/test_env.yaml"
          up-flags: "--build --abort-on-container-exit --exit-code-from test_runner"
